In [2]:
import torch


In [ ]:
x=torch.zeros(2,1)
y=torch.ones(3,5)
z=torch.rand(1,2,dtype=torch.float16)
print(x)
print(y)
print(z)
print(x.size()) #torch.Size([5, 3]) 元组

tensor([[0.],
        [0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.4409, 0.8687]], dtype=torch.float16)
torch.Size([2, 1])


In [ ]:
# 加法
x=torch.rand(5,3)
y=torch.ones_like(x)
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)
# 与x+y等价
print(x+y)

tensor([[1.0410, 1.7331, 1.8225],
        [1.8556, 1.8997, 1.1807],
        [1.3584, 1.5901, 1.9043],
        [1.3267, 1.0381, 1.8349],
        [1.6937, 1.1482, 1.4644]])
tensor([[1.0410, 1.7331, 1.8225],
        [1.8556, 1.8997, 1.1807],
        [1.3584, 1.5901, 1.9043],
        [1.3267, 1.0381, 1.8349],
        [1.6937, 1.1482, 1.4644]])


In [6]:
# 原地加法 add_
y.add_(x)
print(y)

tensor([[1.0410, 1.7331, 1.8225],
        [1.8556, 1.8997, 1.1807],
        [1.3584, 1.5901, 1.9043],
        [1.3267, 1.0381, 1.8349],
        [1.6937, 1.1482, 1.4644]])


In [ ]:
#索引 
# 用list即括号[]索引
# 逗号隔开的代表一个维度，先行后列
print(x[0,1])


# 切片索引
# 切片的基本语法是 start:stop:step，其中：
# start：切片开始的索引（包含该位置）。
# stop：切片结束的索引（不包含该位置）。
# step：步长，指定在选择过程中跳过多少个元素。
# step=1：默认情况下，步长为 1，表示连续选择元素。
# step>1：表示在选择元素时会跳过一定数量的元素。
# step<0：表示反向切片，从右往左选择元素。

x = torch.tensor([1, 2, 3, 4, 5, 6])
# 从第一个开始，每2步选择1个元素
print(x[::2])  # 输出 tensor([1, 3, 5])
# 从最后一个元素开始选择，直到第一个元素。
print(x[::-1])  # 输出 tensor([6, 5, 4, 3, 2, 1])
# 从索引 1 到索引 5，步长为 2 
print(x[1:5:2])  # 输出 tensor([2, 4])


In [ ]:
# 多维切片